### ISSUE TITLE
在android 4.4上不生效

### ISSUE THREAD

**Issue by AllenChow** [pqpo/InputMethodHolder#1]
``06-19 10:25:56.721 12910-12910/pw.qlm.softinputmethodlistener W/InputMethodHolder: hook failed! detail:java.lang.ClassNotFoundException: android.app.SystemServiceRegistry
                                                                                       at java.lang.Class.classForName(Native Method)
                                                                                       at java.lang.Class.forName(Class.java:251)
                                                                                       at java.lang.Class.forName(Class.java:216)
                                                                                       at pw.qlm.inputmethodholder.compat.SystemServiceRegistryCompat.Class(SystemServiceRegistryCompat.java:17)
                                                                                       at pw.qlm.inputmethodholder.compat.SystemServiceRegistryCompat.getSystemFetcher(SystemServiceRegistryCompat.java:23)
                                                                                       at pw.qlm.inputmethodholder.hook.InputMethodManagerHook.clearCachedService(InputMethodManagerHook.java:70)
                                                                                       at pw.qlm.inputmethodholder.hook.InputMethodManagerHook.onHook(InputMethodManagerHook.java:60)
                                                                                       at pw.qlm.inputmethodholder.InputMethodHolder.init(InputMethodHolder.java:41)
                                                                                       at pw.qlm.sample.MyApplication.attachBaseContext(MyApplication.java:18)
                                                                                       at android.app.Application.attach(Application.java:181)
                                                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:991)
                                                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:975)
                                                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:502)
                                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301)
                                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                                    Caused by: java.lang.NoClassDefFoundError: android/app/SystemServiceRegistry
                                                                                       at java.lang.Class.classForName(Native Method) 
                                                                                       at java.lang.Class.forName(Class.java:251) 
                                                                                       at java.lang.Class.forName(Class.java:216) 
                                                                                       at pw.qlm.inputmethodholder.compat.SystemServiceRegistryCompat.Class(SystemServiceRegistryCompat.java:17) 
                                                                                       at pw.qlm.inputmethodholder.compat.SystemServiceRegistryCompat.getSystemFetcher(SystemServiceRegistryCompat.java:23) 
                                                                                       at pw.qlm.inputmethodholder.hook.InputMethodManagerHook.clearCachedService(InputMethodManagerHook.java:70) 
                                                                                       at pw.qlm.inputmethodholder.hook.InputMethodManagerHook.onHook(InputMethodManagerHook.java:60) 
                                                                                       at pw.qlm.inputmethodholder.InputMethodHolder.init(InputMethodHolder.java:41) 
                                                                                       at pw.qlm.sample.MyApplication.attachBaseContext(MyApplication.java:18) 
                                                                                       at android.app.Application.attach(Application.java:181) 
                                                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
                                                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
                                                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.SystemServiceRegistry" on path: DexPathList[[zip file "/data/app/pw.qlm.softinputmethodlistener-1.apk"],nativeLibraryDirectories=[/data/app-lib/pw.qlm.softinputmethodlistener-1, /vendor/lib, /system/lib]]
                                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                                       at java.lang.Class.classForName(Native Method) 
                                                                                       at java.lang.Class.forName(Class.java:251) 
                                                                                       at java.lang.Class.forName(Class.java:216) 
                                                                                       at pw.qlm.inputmethodholder.compat.SystemServiceRegistryCompat.Class(SystemServiceRegistryCompat.java:17) 
                                                                                       at pw.qlm.inputmethodholder.compat.SystemServiceRegistryCompat.getSystemFetcher(SystemServiceRegistryCompat.java:23) 
                                                                                       at pw.qlm.inputmethodholder.hook.InputMethodManagerHook.clearCachedService(InputMethodManagerHook.java:70) 
                                                                                       at pw.qlm.inputmethodholder.hook.InputMethodManagerHook.onHook(InputMethodManagerHook.java:60) 
                                                                                       at pw.qlm.inputmethodholder.InputMethodHolder.init(InputMethodHolder.java:41) 
                                                                                       at pw.qlm.sample.MyApplication.attachBaseContext(MyApplication.java:18) 
                                                                                       at android.app.Application.attach(Application.java:181) 
                                                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:991) 
                                                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:975) 
                                                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:502) 
                                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4301) 
                                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                                       at dalvik.system.NativeStart.main(Native Method) 
06-19 10:25:56.731 12910-1``

**Comment by pqpo** [comment]
已修复，你可以再看一下。原因是4.4及以下机型没有SystemServiceRegistry类，直接在ContextImpl中使用静态map保存所有service。本库由于是Hook系统服务完成，可能存在其他未知的兼容性问题，谨慎用于生产。
